---
# Source: oes/templates/secrets/opsmx-gitops-secret.yaml
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  gitcloneparam: https://YOUR_USER_NAME:encrypted%3Agittoken%3Agittoken@github.com/YOUR_ORG_NAME_OR_YOUR_USER_NAME_IF_NO_ORG/YOUR_REPO_NAME.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://github.com/YOUR_ORG_NAME_OR_YOUR_USER_NAME_IF_NO_ORG/SAME_AS_REPOSITORY_ABOVE.git
  gituser: YOUR_USER_NAME
  gittoken: encrypted:gittoken:gittoken
  dynamicAccRepository: SAME_AS_REPOSITORY_ABOVE

kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
