---
# Source: oes/templates/secrets/opsmx-gitops-secret.yaml
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  gitcloneparam: https://yugaa22:encrypted%3Agittoken%3Agittoken@github.com/yugaa22/standard-isd-gitops.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://github.com/yugaa22/standard-isd-gitops.git
  gituser: yugaa22
  gittoken: encrypted:gittoken:gittoken
  dynamicAccRepository: standard-isd-gitops

kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
