---
# Source: oes/templates/deployments/opa-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opa
    heritage: "Helm"
    release: "isd"
    chart: "oes-3.11.4"
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
        heritage: "Helm"
        release: "isd"
        chart: "oes-3.11.4"
      name: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:edge-rootless
          args:
            - "run"
            - "--server"
        - name: opa-persist
          command: 
          - /bin/bash
          - /tmp/config/opa-persist.sh
          envFrom:
          - secretRef:
              name: oes-gate-secret
          image: quay.io/opsmxpublic/customterraformstage:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /tmp/config
            name: opa-persist
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: opa-persist
          name: opa-persist
